/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cit260.winter2015.minesweeper.swing;

import cit260.winter2015.minesweeper.exceptions.EndGameException;
import cit260.winter2015.minesweeper.menuControls.LevelSelectionControl;
import static cit260.winter2015.minesweeper.swing.MainFrame.mainPanel;

/**
 *
 * @author Cheryl Rubenstein and Nikki Huntsman
 */
public class BestTimesMenu extends javax.swing.JPanel {

    /**
     * Creates new form LevelSelection
     */
    public BestTimesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpButtonPanel = new javax.swing.JPanel();
        jbBeginnerBestTimes = new javax.swing.JButton();
        jbIntermediateBestTimes = new javax.swing.JButton();
        jbExpertBestTimes = new javax.swing.JButton();
        jbAllBestTimes = new javax.swing.JButton();
        jbQuitToMain = new javax.swing.JButton();
        jpTitlePanel = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jViewCard = new javax.swing.JPanel();
        jpBestTimesInstructions = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBestTimes = new javax.swing.JTextArea();
        jpBegBestTimes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpIntBestTimes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jpExpBestTimes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jpAllBestTimes = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 51, 153));
        setPreferredSize(new java.awt.Dimension(500, 400));

        jpButtonPanel.setBackground(new java.awt.Color(0, 51, 153));

        jbBeginnerBestTimes.setText("Beginner Best Times");
        jbBeginnerBestTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBeginnerBestTimesActionPerformed(evt);
            }
        });

        jbIntermediateBestTimes.setText("Intermediate Best Times");
        jbIntermediateBestTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIntermediateBestTimesActionPerformed(evt);
            }
        });

        jbExpertBestTimes.setText("Expert Best Times");
        jbExpertBestTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExpertBestTimesActionPerformed(evt);
            }
        });

        jbAllBestTimes.setText("All Best Times");
        jbAllBestTimes.setActionCommand("All Best Times");
        jbAllBestTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAllBestTimesActionPerformed(evt);
            }
        });

        jbQuitToMain.setText("Quit to Main Menu");
        jbQuitToMain.setToolTipText("");
        jbQuitToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonPanelLayout = new javax.swing.GroupLayout(jpButtonPanel);
        jpButtonPanel.setLayout(jpButtonPanelLayout);
        jpButtonPanelLayout.setHorizontalGroup(
            jpButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbBeginnerBestTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbIntermediateBestTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbExpertBestTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbAllBestTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbQuitToMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpButtonPanelLayout.setVerticalGroup(
            jpButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonPanelLayout.createSequentialGroup()
                .addComponent(jbBeginnerBestTimes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbIntermediateBestTimes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExpertBestTimes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAllBestTimes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbQuitToMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTitlePanel.setBackground(new java.awt.Color(0, 51, 153));
        jpTitlePanel.setPreferredSize(new java.awt.Dimension(500, 46));
        jpTitlePanel.setLayout(new java.awt.BorderLayout());

        jlTitle.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(240, 240, 240));
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Minesweeper");
        jlTitle.setToolTipText("");
        jlTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlTitle.setMaximumSize(new java.awt.Dimension(2000, 37));
        jpTitlePanel.add(jlTitle, java.awt.BorderLayout.CENTER);

        jViewCard.setLayout(new java.awt.CardLayout());

        jBestTimes.setEditable(false);
        jBestTimes.setColumns(20);
        jBestTimes.setLineWrap(true);
        jBestTimes.setRows(5);
        jBestTimes.setText("Please click the link on the left to view the top ten best times for that level.");
        jBestTimes.setToolTipText("");
        jBestTimes.setWrapStyleWord(true);
        jBestTimes.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jBestTimes);

        javax.swing.GroupLayout jpBestTimesInstructionsLayout = new javax.swing.GroupLayout(jpBestTimesInstructions);
        jpBestTimesInstructions.setLayout(jpBestTimesInstructionsLayout);
        jpBestTimesInstructionsLayout.setHorizontalGroup(
            jpBestTimesInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jpBestTimesInstructionsLayout.setVerticalGroup(
            jpBestTimesInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jViewCard.add(jpBestTimesInstructions, "BTInstructions");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jpBegBestTimesLayout = new javax.swing.GroupLayout(jpBegBestTimes);
        jpBegBestTimes.setLayout(jpBegBestTimesLayout);
        jpBegBestTimesLayout.setHorizontalGroup(
            jpBegBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jpBegBestTimesLayout.setVerticalGroup(
            jpBegBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        jViewCard.add(jpBegBestTimes, "BegCard");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jpIntBestTimesLayout = new javax.swing.GroupLayout(jpIntBestTimes);
        jpIntBestTimes.setLayout(jpIntBestTimesLayout);
        jpIntBestTimesLayout.setHorizontalGroup(
            jpIntBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jpIntBestTimesLayout.setVerticalGroup(
            jpIntBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        jViewCard.add(jpIntBestTimes, "IntCard");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jpExpBestTimesLayout = new javax.swing.GroupLayout(jpExpBestTimes);
        jpExpBestTimes.setLayout(jpExpBestTimesLayout);
        jpExpBestTimesLayout.setHorizontalGroup(
            jpExpBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jpExpBestTimesLayout.setVerticalGroup(
            jpExpBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        jViewCard.add(jpExpBestTimes, "ExpCard");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout jpAllBestTimesLayout = new javax.swing.GroupLayout(jpAllBestTimes);
        jpAllBestTimes.setLayout(jpAllBestTimesLayout);
        jpAllBestTimesLayout.setHorizontalGroup(
            jpAllBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jpAllBestTimesLayout.setVerticalGroup(
            jpAllBestTimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAllBestTimesLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jViewCard.add(jpAllBestTimes, "AllBTCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jViewCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addComponent(jpTitlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jpButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jViewCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbBeginnerBestTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBeginnerBestTimesActionPerformed
     jViewCard.show(jViewCard,"BegCard");
     jViewCard.
    }//GEN-LAST:event_jbBeginnerBestTimesActionPerformed

    private void jbIntermediateBestTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIntermediateBestTimesActionPerformed
        try {
            LevelSelectionControl.intermediate();
        } catch (EndGameException ex) {
            // Todo
        }
    }//GEN-LAST:event_jbIntermediateBestTimesActionPerformed

    private void jbExpertBestTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExpertBestTimesActionPerformed
        try {
            LevelSelectionControl.expert();
        } catch (EndGameException ex) {
            // Todo
        }
    }//GEN-LAST:event_jbExpertBestTimesActionPerformed

    private void jbAllBestTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAllBestTimesActionPerformed
        try {
            LevelSelectionControl.beginnerPreset();
        } catch (EndGameException ex) {
            // Todo
        }
    }//GEN-LAST:event_jbAllBestTimesActionPerformed

    private void jbQuitToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitToMainActionPerformed
        MainFrame.card.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_jbQuitToMainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jBestTimes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel jViewCard;
    private javax.swing.JButton jbAllBestTimes;
    private javax.swing.JButton jbBeginnerBestTimes;
    private javax.swing.JButton jbExpertBestTimes;
    private javax.swing.JButton jbIntermediateBestTimes;
    private javax.swing.JButton jbQuitToMain;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpAllBestTimes;
    private javax.swing.JPanel jpBegBestTimes;
    private javax.swing.JPanel jpBestTimesInstructions;
    private javax.swing.JPanel jpButtonPanel;
    private javax.swing.JPanel jpExpBestTimes;
    private javax.swing.JPanel jpIntBestTimes;
    private javax.swing.JPanel jpTitlePanel;
    // End of variables declaration//GEN-END:variables
}
