/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cit260.winter2015.minesweeper.swing;

import cit260.winter2015.minesweeper.enums.HelpType;
import static cit260.winter2015.minesweeper.swing.MainFrame.mainPanel;
import java.awt.CardLayout;

/**
 *
 * @author knban_000
 */
public class HelpMenu extends javax.swing.JPanel {

    /**
     * Creates new form LevelSelection
     */
    public HelpMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpTitlePanel = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpButtonPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbHowToPlay = new javax.swing.JButton();
        jbBasicStrategies = new javax.swing.JButton();
        jbAboutTheDevelopers = new javax.swing.JButton();
        jbQuitToMain = new javax.swing.JButton();
        jpViewCard = new javax.swing.JPanel();
        jpMenuInstructions = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jpHowToPlay = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBestTimes = new javax.swing.JTextArea();
        jpBasicStrategies = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpAboutTheDevelopers = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 51, 153));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new java.awt.GridBagLayout());

        jpTitlePanel.setBackground(new java.awt.Color(0, 51, 153));
        jpTitlePanel.setMinimumSize(new java.awt.Dimension(250, 46));
        jpTitlePanel.setName(""); // NOI18N
        jpTitlePanel.setPreferredSize(new java.awt.Dimension(500, 46));
        jpTitlePanel.setLayout(new java.awt.GridBagLayout());

        jlTitle.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(240, 240, 240));
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Minesweeper");
        jlTitle.setToolTipText("");
        jlTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlTitle.setMaximumSize(new java.awt.Dimension(2000, 37));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpTitlePanel.add(jlTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jpTitlePanel, gridBagConstraints);

        jpButtonPanel.setBackground(new java.awt.Color(0, 51, 153));
        jpButtonPanel.setMinimumSize(new java.awt.Dimension(150, 50));
        jpButtonPanel.setPreferredSize(new java.awt.Dimension(150, 50));
        java.awt.GridBagLayout jpButtonPanelLayout = new java.awt.GridBagLayout();
        jpButtonPanelLayout.columnWidths = new int[] {150};
        jpButtonPanel.setLayout(jpButtonPanelLayout);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Help Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jpButtonPanel.add(jLabel2, gridBagConstraints);

        jbHowToPlay.setText("How to Play");
        jbHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHowToPlayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbHowToPlay, gridBagConstraints);

        jbBasicStrategies.setText("Basic Strategies");
        jbBasicStrategies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBasicStrategiesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbBasicStrategies, gridBagConstraints);

        jbAboutTheDevelopers.setText("About the Developers");
        jbAboutTheDevelopers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAboutTheDevelopersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbAboutTheDevelopers, gridBagConstraints);

        jbQuitToMain.setText("Quit to Main Menu");
        jbQuitToMain.setToolTipText("");
        jbQuitToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitToMainActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbQuitToMain, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jpButtonPanel, gridBagConstraints);

        jpViewCard.setBackground(new java.awt.Color(0, 51, 153));
        jpViewCard.setLayout(new java.awt.CardLayout());

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Please click one of the buttons on the left to view a help topic.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextArea3.setName(""); // NOI18N
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jpMenuInstructionsLayout = new javax.swing.GroupLayout(jpMenuInstructions);
        jpMenuInstructions.setLayout(jpMenuInstructionsLayout);
        jpMenuInstructionsLayout.setHorizontalGroup(
            jpMenuInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jpMenuInstructionsLayout.setVerticalGroup(
            jpMenuInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        jpViewCard.add(jpMenuInstructions, "helpMenuInstructions");

        jBestTimes.setEditable(false);
        jBestTimes.setColumns(20);
        jBestTimes.setLineWrap(true);
        jBestTimes.setRows(5);
        jBestTimes.setText(HelpType.HOW_TO_PLAY.getHelpText());
        jBestTimes.setToolTipText("");
        jBestTimes.setWrapStyleWord(true);
        jBestTimes.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jBestTimes);

        javax.swing.GroupLayout jpHowToPlayLayout = new javax.swing.GroupLayout(jpHowToPlay);
        jpHowToPlay.setLayout(jpHowToPlayLayout);
        jpHowToPlayLayout.setHorizontalGroup(
            jpHowToPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jpHowToPlayLayout.setVerticalGroup(
            jpHowToPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        jpViewCard.add(jpHowToPlay, "howToPlay");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(HelpType.BASIC_STRATEGIES.getHelpText());
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jpBasicStrategiesLayout = new javax.swing.GroupLayout(jpBasicStrategies);
        jpBasicStrategies.setLayout(jpBasicStrategiesLayout);
        jpBasicStrategiesLayout.setHorizontalGroup(
            jpBasicStrategiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jpBasicStrategiesLayout.setVerticalGroup(
            jpBasicStrategiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        jpViewCard.add(jpBasicStrategies, "basicStrategies");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText(HelpType.ABOUT.getHelpText());
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jpAboutTheDevelopersLayout = new javax.swing.GroupLayout(jpAboutTheDevelopers);
        jpAboutTheDevelopers.setLayout(jpAboutTheDevelopersLayout);
        jpAboutTheDevelopersLayout.setHorizontalGroup(
            jpAboutTheDevelopersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jpAboutTheDevelopersLayout.setVerticalGroup(
            jpAboutTheDevelopersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        jpViewCard.add(jpAboutTheDevelopers, "aboutTheDevelopers");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        add(jpViewCard, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jbHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHowToPlayActionPerformed
        CardLayout cl =(CardLayout)(jpViewCard.getLayout());
        cl.show(jpViewCard, "howToPlay");
    }//GEN-LAST:event_jbHowToPlayActionPerformed

    private void jbBasicStrategiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBasicStrategiesActionPerformed
        CardLayout cl =(CardLayout)(jpViewCard.getLayout());
        cl.show(jpViewCard, "basicStrategies");
    }//GEN-LAST:event_jbBasicStrategiesActionPerformed

    private void jbAboutTheDevelopersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAboutTheDevelopersActionPerformed
        CardLayout cl =(CardLayout)(jpViewCard.getLayout());
        cl.show(jpViewCard, "aboutTheDevelopers");
    }//GEN-LAST:event_jbAboutTheDevelopersActionPerformed

    private void jbQuitToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitToMainActionPerformed
        MainFrame.card.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_jbQuitToMainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jBestTimes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton jbAboutTheDevelopers;
    private javax.swing.JButton jbBasicStrategies;
    private javax.swing.JButton jbHowToPlay;
    private javax.swing.JButton jbQuitToMain;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpAboutTheDevelopers;
    private javax.swing.JPanel jpBasicStrategies;
    private javax.swing.JPanel jpButtonPanel;
    private javax.swing.JPanel jpHowToPlay;
    private javax.swing.JPanel jpMenuInstructions;
    private javax.swing.JPanel jpTitlePanel;
    private javax.swing.JPanel jpViewCard;
    // End of variables declaration//GEN-END:variables
}
