/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cit260.winter2015.minesweeper.swing;

import cit260.winter2015.minesweeper.GameVariables;
import cit260.winter2015.minesweeper.Minesweeper;
import cit260.winter2015.minesweeper.enums.LevelType;
import static cit260.winter2015.minesweeper.swing.MainFrame.mainPanel;
import java.awt.Dimension;

/**
 *
 * @author knban_000
 */
public class InGame extends javax.swing.JPanel {

    
    /**
     * Creates new form MainMenu
     */
    public InGame() {
        initComponents();
    }
    
    public void startGame() {
        Minesweeper.mm.generateMines();
        Minesweeper.cm.calculateCellValues();
        Minesweeper.cm.loadImages();
        Minesweeper.cm.setStatusBarMinesRemaining();
        statusBar.setText("Mines Remaining: " + GameVariables.getNumberOfMines());
        jpBoard.setPreferredSize(new Dimension(GameVariables.getNumberOfColumns() * LevelType.CELL_SIZE, GameVariables.getNumberOfRows() * LevelType.CELL_SIZE));
        System.out.println("Number of Columns: " + GameVariables.getNumberOfColumns() + ", width: " + jpBoard.getWidth());
        Minesweeper.mainFrame.resizeWindow(jpBoard.getWidth() + 10, jpBoard.getHeight() + 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitlePanel = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpBottomBar = new javax.swing.JPanel();
        jbMainMenu = new javax.swing.JButton();
        jbPause = new javax.swing.JButton();
        statusBar = new javax.swing.JLabel();
        jpBoard = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 51, 153));

        jpTitlePanel.setBackground(new java.awt.Color(0, 51, 153));

        jlTitle.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(240, 240, 240));
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Minesweeper");
        jlTitle.setToolTipText("");
        jlTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlTitle.setMaximumSize(new java.awt.Dimension(2000, 37));

        javax.swing.GroupLayout jpTitlePanelLayout = new javax.swing.GroupLayout(jpTitlePanel);
        jpTitlePanel.setLayout(jpTitlePanelLayout);
        jpTitlePanelLayout.setHorizontalGroup(
            jpTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpTitlePanelLayout.setVerticalGroup(
            jpTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitlePanelLayout.createSequentialGroup()
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpBottomBar.setBackground(new java.awt.Color(0, 51, 153));

        jbMainMenu.setText("Quit to MainMenu");
        jbMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMainMenuActionPerformed(evt);
            }
        });

        jbPause.setText("Pause");
        jbPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPauseActionPerformed(evt);
            }
        });

        statusBar.setBackground(new java.awt.Color(0, 51, 153));
        statusBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        statusBar.setForeground(new java.awt.Color(255, 255, 255));
        statusBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusBar.setText("Mines Remaining: " + GameVariables.getNumberOfMines());
        statusBar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jpBottomBarLayout = new javax.swing.GroupLayout(jpBottomBar);
        jpBottomBar.setLayout(jpBottomBarLayout);
        jpBottomBarLayout.setHorizontalGroup(
            jpBottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBottomBarLayout.createSequentialGroup()
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBottomBarLayout.setVerticalGroup(
            jpBottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpBottomBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpBottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMainMenu)
                    .addComponent(jbPause)))
            .addGroup(jpBottomBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusBar))
        );

        javax.swing.GroupLayout jpBoardLayout = new javax.swing.GroupLayout(jpBoard);
        jpBoard.setLayout(jpBoardLayout);
        jpBoardLayout.setHorizontalGroup(
            jpBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jpBoardLayout.setVerticalGroup(
            jpBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpBottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMainMenuActionPerformed
        MainFrame.card.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_jbMainMenuActionPerformed

    private void jbPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPauseActionPerformed
        System.out.println(GameVariables.getNumberOfMines());
//        MainFrame.card.show(mainPanel, "paused");
    }//GEN-LAST:event_jbPauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbMainMenu;
    private javax.swing.JButton jbPause;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBoard;
    private javax.swing.JPanel jpBottomBar;
    private javax.swing.JPanel jpTitlePanel;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
