/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cit260.winter2015.minesweeper.swing;

import cit260.winter2015.minesweeper.GameVariables;
import cit260.winter2015.minesweeper.Minesweeper;
import cit260.winter2015.minesweeper.enums.LevelType;
import static cit260.winter2015.minesweeper.enums.LevelType.BEGINNER;
import static cit260.winter2015.minesweeper.swing.MainFrame.mainPanel;

/**
 *
 * @author knban_000
 */
public class LevelSelection extends javax.swing.JPanel {


    /**
     * Creates new form LevelSelection
     */
    public LevelSelection() {
        
        initComponents();
    }

    public void playGame() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpTitlePanel = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbBeginner = new javax.swing.JButton();
        jbIntermediate = new javax.swing.JButton();
        jbExpert = new javax.swing.JButton();
        jbPreset = new javax.swing.JButton();
        jbQuitToMain = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 51, 153));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new java.awt.GridBagLayout());

        jpTitlePanel.setBackground(new java.awt.Color(0, 51, 153));
        jpTitlePanel.setMinimumSize(new java.awt.Dimension(250, 46));
        jpTitlePanel.setPreferredSize(new java.awt.Dimension(500, 46));
        jpTitlePanel.setLayout(new java.awt.GridBagLayout());

        jlTitle.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(240, 240, 240));
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Minesweeper");
        jlTitle.setToolTipText("");
        jlTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlTitle.setMaximumSize(new java.awt.Dimension(2000, 37));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpTitlePanel.add(jlTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jpTitlePanel, gridBagConstraints);

        jpButtonPanel.setBackground(new java.awt.Color(0, 51, 153));
        jpButtonPanel.setMinimumSize(new java.awt.Dimension(150, 140));
        jpButtonPanel.setName(""); // NOI18N
        jpButtonPanel.setPreferredSize(new java.awt.Dimension(150, 140));
        java.awt.GridBagLayout jpButtonPanelLayout = new java.awt.GridBagLayout();
        jpButtonPanelLayout.columnWidths = new int[] {150};
        jpButtonPanel.setLayout(jpButtonPanelLayout);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Level Selection");
        jpButtonPanel.add(jLabel1, new java.awt.GridBagConstraints());

        jbBeginner.setText("Beginner");
        jbBeginner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBeginnerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbBeginner, gridBagConstraints);

        jbIntermediate.setText("Intermediate");
        jbIntermediate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIntermediateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbIntermediate, gridBagConstraints);

        jbExpert.setText("Expert");
        jbExpert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExpertActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbExpert, gridBagConstraints);

        jbPreset.setText("Preset Beginner");
        jbPreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPresetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbPreset, gridBagConstraints);

        jbQuitToMain.setText("Quit to Main Menu");
        jbQuitToMain.setToolTipText("");
        jbQuitToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitToMainActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpButtonPanel.add(jbQuitToMain, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jpButtonPanel, gridBagConstraints);
        jpButtonPanel.getAccessibleContext().setAccessibleDescription("");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Select the difficulty level you would like to play.");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextArea1.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        add(jTextArea1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jbBeginnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBeginnerActionPerformed
        LevelType.setBeginner();
        MainFrame.card.show(mainPanel, "inGame");
        MainFrame.inGame.startGame();
        Minesweeper.mainFrame.resizeWindow(400, 450);
    }//GEN-LAST:event_jbBeginnerActionPerformed

    private void jbIntermediateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIntermediateActionPerformed
        LevelType.setIntermediate();
        MainFrame.card.show(mainPanel, "inGame");
        MainFrame.inGame.startGame();
        Minesweeper.mainFrame.resizeWindow(500, 635);
    }//GEN-LAST:event_jbIntermediateActionPerformed

    private void jbExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExpertActionPerformed
        LevelType.setExpert();
        MainFrame.card.show(mainPanel, "inGame");
        MainFrame.inGame.startGame();
        Minesweeper.mainFrame.resizeWindow(900, 635);
    }//GEN-LAST:event_jbExpertActionPerformed

    private void jbPresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPresetActionPerformed
        GameVariables.setGameVariables("preset beginner", BEGINNER.getRows(), BEGINNER.getColumns(), BEGINNER.getMines());
        MainFrame.card.show(mainPanel, "inGame");
        MainFrame.inGame.startGamePreset();
        Minesweeper.mainFrame.resizeWindow(400, 450);
    }//GEN-LAST:event_jbPresetActionPerformed

    private void jbQuitToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitToMainActionPerformed
        MainFrame.card.show(mainPanel, "mainMenu");
    }//GEN-LAST:event_jbQuitToMainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbBeginner;
    private javax.swing.JButton jbExpert;
    private javax.swing.JButton jbIntermediate;
    private javax.swing.JButton jbPreset;
    private javax.swing.JButton jbQuitToMain;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpButtonPanel;
    private javax.swing.JPanel jpTitlePanel;
    // End of variables declaration//GEN-END:variables
}
