/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cit260.winter2015.minesweeper.swing;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.*;

/**
 *
 * @author knban_000
 */
public class MainFrame extends JFrame {

    public static JPanel mainPanel;
    static CardLayout card;
    
    // Declare all cards that will be used in GUI
    static MainMenu mainMenu;
    static LevelSelection levelSelection;
    static BestTimesMenu bestTimesMenu;
    static HelpMenu helpMenu;
    static InGame inGame;
    static Paused paused;
    
    public MainFrame() {
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Minesweeper");
        setPreferredSize(new Dimension(500,400));
        setMinimumSize(new Dimension(300, 200));
        setMaximumSize(null);
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        pack();
        setVisible(true);
        
        mainPanel = new JPanel();
        mainPanel.setBackground(new java.awt.Color(0, 51, 153));
        mainPanel.setBounds(0, 0, 500, 400);
        
        // Assign class location to variable for each panel or card.
        mainMenu = new MainMenu();
        levelSelection = new LevelSelection();
        bestTimesMenu = new BestTimesMenu();
        helpMenu = new HelpMenu();
        inGame = new InGame();
        paused = new Paused();
        
        card = new CardLayout();
        mainPanel.setLayout(card);
        setContentPane(mainPanel);
        
        // Assign card name to each card or panel.
        mainPanel.add(mainMenu, "mainMenu");
        mainPanel.add(levelSelection, "levelSelection");
        mainPanel.add(bestTimesMenu, "bestTimesMenu");
        mainPanel.add(helpMenu, "helpMenu");
        mainPanel.add(inGame, "inGame");
        mainPanel.add(paused, "paused");
    }
    
    public void resizeWindow(int width, int height) {
        setPreferredSize(new Dimension(width, height));
        revalidate();
        repaint();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu1 = new cit260.winter2015.minesweeper.swing.MainMenu();
        levelSelection1 = new cit260.winter2015.minesweeper.swing.LevelSelection();
        bestTimesMenu1 = new cit260.winter2015.minesweeper.swing.BestTimesMenu();
        helpMenu1 = new cit260.winter2015.minesweeper.swing.HelpMenu();
        inGame1 = new cit260.winter2015.minesweeper.swing.InGame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(mainMenu1, "card2");
        getContentPane().add(levelSelection1, "card3");
        getContentPane().add(bestTimesMenu1, "card4");
        getContentPane().add(helpMenu1, "card5");
        getContentPane().add(inGame1, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cit260.winter2015.minesweeper.swing.BestTimesMenu bestTimesMenu1;
    private cit260.winter2015.minesweeper.swing.HelpMenu helpMenu1;
    private cit260.winter2015.minesweeper.swing.InGame inGame1;
    private cit260.winter2015.minesweeper.swing.LevelSelection levelSelection1;
    private cit260.winter2015.minesweeper.swing.MainMenu mainMenu1;
    // End of variables declaration//GEN-END:variables
}
