/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cit260.winter2015.minesweeper.swing;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author knban_000
 */
public class MainFrame extends JFrame {

    public static JPanel mainPanel;
    static MainMenu mainMenu;
    static LevelSelection levelSelection;
    static CardLayout card;
    
    public MainFrame() {
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Minesweeper");
        setPreferredSize(new Dimension(500,400));
        setMinimumSize(new Dimension(300, 200));
        setMaximumSize(null);
        setLayout(null);   
        setLocationRelativeTo(null);
        setResizable(true);
        pack();
        setVisible(true);
        
        mainPanel = new JPanel();
        mainPanel.setBackground(new java.awt.Color(0, 51, 153));
        mainPanel.setBounds(0, 0, 500, 400);
        
        mainMenu = new cit260.winter2015.minesweeper.swing.MainMenu();
        levelSelection = new cit260.winter2015.minesweeper.swing.LevelSelection();
        
        card = new CardLayout();
        mainPanel.setLayout(card);
//        add(mainPanel);
        setContentPane(mainPanel);
        
        mainPanel.add(mainMenu, "mainMenu");
        mainPanel.add(levelSelection, "levelSelection");

        mainMenu.add(new JLabel("Main Menu"));
        JButton btn1 = new JButton("Show second");
        mainMenu.add(btn1);
        btn1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                card.show(mainPanel, "levelSelection");
            }
        }
        );

        levelSelection.add(new JLabel("Level Selection"));
        JButton btn2 = new JButton("Show First");
        levelSelection.add(btn2);
        btn2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                card.show(mainPanel, "mainMenu");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
